"""Selectable MOBA games and ranks for profile cabinet."""

GAMES: list[dict[str, str]] = [
    {"slug": "mlbb", "name_ru": "Mobile Legends", "name_en": "Mobile Legends"},
    {"slug": "lol", "name_ru": "League of Legends", "name_en": "League of Legends"},
    {"slug": "wildrift", "name_ru": "Wild Rift", "name_en": "Wild Rift"},
    {"slug": "dota2", "name_ru": "Dota 2", "name_en": "Dota 2"},
    {"slug": "aov", "name_ru": "Arena of Valor", "name_en": "Arena of Valor"},
    {"slug": "hok", "name_ru": "Honor of Kings", "name_en": "Honor of Kings"},
    {"slug": "smite", "name_ru": "Smite", "name_en": "Smite"},
]

GAME_SLUGS: frozenset[str] = frozenset(g["slug"] for g in GAMES)

RANKS: dict[str, list[str]] = {
    "mlbb": [
        "Warrior",
        "Elite",
        "Master",
        "Grandmaster",
        "Epic",
        "Legend",
        "Mythic",
        "Mythic 1-24 stars",
        "Mythical Honor",
        "Mythical Glory",
        "Mythical Immortal",
    ],
    "lol": [
        "Iron",
        "Bronze",
        "Silver",
        "Gold",
        "Platinum",
        "Emerald",
        "Diamond",
        "Master",
        "Grandmaster",
        "Challenger",
    ],
    "wildrift": [
        "Iron",
        "Bronze",
        "Silver",
        "Gold",
        "Platinum",
        "Emerald",
        "Diamond",
        "Master",
        "Grandmaster",
        "Challenger",
        "Sovereign",
    ],
    "dota2": [
        "Herald",
        "Guardian",
        "Crusader",
        "Archon",
        "Legend",
        "Ancient",
        "Divine",
        "Immortal",
        "Immortal Top 1000",
        "Immortal Top 100",
    ],
    "aov": [
        "Bronze",
        "Silver",
        "Gold",
        "Platinum",
        "Diamond",
        "Master",
        "Conqueror",
        "Grand Conqueror",
        "Legendary Conqueror",
        "Glorious Conqueror",
    ],
    "hok": [
        "Bronze",
        "Silver",
        "Gold",
        "Platinum",
        "Diamond",
        "Starlight",
        "King",
        "High King",
        "Glory",
        "Mythic",
    ],
    "smite": [
        "Bronze",
        "Silver",
        "Gold",
        "Platinum",
        "Diamond",
        "Masters",
        "Grandmaster",
    ],
}
